language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make clean
- make github-travis
- make clean
- make aws-create
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: gezinsbond-humbeek.be
  region: eu-west-1
  skip_cleanup: true
  local-dir: output
  acl: public_read
  cache_control: "max-age=21600"
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    on_failure: change
    on_success: change
env:
  global:
    secure: igigAwlnLvCE5CMOIECCaOhcRkTyvLnHvdOj+Aul595wvL18Cc5NIjbu9w03RhbbtZLu1Yg2i5XZ+KYX1X4H9ag4c++etONhiTY64PYe9qepQdm3Mktul0KFAAv1H6PhFwvFgN89lxpgNFQA2/xKvAOs2iF9BfVV52OatjVVSlJWKAQxD4LJEVTJTJNUrS6zJW/7J0m5pVdqAQn49z73z6E2yHmfTWxJuul9tiewBVl4fj2bkB3nvFhj279TsRUeMu5CVVAZKaigy6Aqvy9zrO+4AdwlSYCRE/myT+lUvg5XfIYcW5q7TB5p6qKLptg7byA6TGYgmgtO4xXfusHwjOWopO64zEjXUwPXW2dVlTSYcNqnfz8cEYAqjrearCw1Mb4TKDcrMZeiiUjIC65jKe2sVNE0qkdEcJSqh4ZekqSWIC1wfiWhK1VUf7hnJwDaXHVzOcJP7VqsutIjTDWvEkMEoFCyGBbh3Cl/hR6hdqAYx7TcItRh0rW+7vLxb2i3BrFGZthjTaGxsLM/2IaOrCr/1w8RUFPoGIjGwAHbiGwPqy5CVLHJzKg43+3shUC/HGtP9cFnTsby7NYwa4l9Cgymslj8mlmpFUv2GijtqCLC3mcFNzYo8+sokuJ7NbKRbW3ODWw+xP5H94aTOUyd5wUsISWYZ1F1IgjRYsVO5JQ=
